// Kamera (Stufe 1, nur App) und der Calima-Look als Rezept in der Datei
export const CAMERA: Record<string, string> = {
  "Calima darf die Kamera nicht nutzen. Erlaube sie in den Einstellungen des iPhones unter Calima.": "Calima isn't allowed to use the camera. Allow it in the iPhone's Settings under Calima.",
  "Die Kamera lässt sich gerade nicht öffnen.": "The camera can't be opened right now.",
  "Das Foto ließ sich nicht aufnehmen. Versuch es noch einmal.": "The photo couldn't be taken. Try again.",
  "Loslassen bringt den Look zurück": "Let go to bring the look back",
  "Zoom {factor}": "Zoom {factor}",
  "Kamera öffnet …": "Opening camera …",
  Looks: "Looks",
  Auslösen: "Shutter",
  Rückkamera: "Back camera",
  Frontkamera: "Front camera",
  "{n} im Stapel. Schließen bringt dich zu Fertig.": "{n} in the stack. Close to get to Done.",
  "Halten zeigt das Original, Wischen macht heller oder dunkler.": "Hold to see the original, swipe to go brighter or darker.",
  "Calima-Look": "Calima look",
  "{label} „{name}“ mitgenommen. Liegt oben bei „Deine Looks“.": "{label} “{name}” taken along. It's up under “Your looks”.",
  "Aus der Datei gelesen, in Calima nachempfunden": "Read from the file, approximated in Calima",
  "Aus der Datei gelesen, so wie das Foto gesichert wurde": "Read from the file, just as the photo was saved",
  "So fotografieren": "Shoot like this",
  "Für die Kamera brauchst du ein Konto. Mitgenommen ist der Look trotzdem.": "The camera needs an account. The look is taken along anyway.",
  "Das Foto liegt im Fotostudio.": "The photo is in the photo studio.",
  "Die {n} Fotos liegen als Stapel im Fotostudio.": "The {n} photos are a stack in the photo studio.",
  "Der Film liegt im Fotostudio.": "The film is in the photo studio.",
  "Calima-Look mitnehmen": "Take the Calima look along",
  "Farbe und Licht ohne Zuschnitt, so wie das Foto gesichert wurde.": "Colour and light without the crop, just as the photo was saved.",
  // Film einlegen (Stufe 2)
  "Film, {i} von {n}": "Film, {i} of {n}",
  "{i} von {n}": "{i} of {n}",
  "Film einlegen": "Load film",
  "Film entnehmen": "Take out film",
  "Film raus": "Film out",
  "Der Film bleibt drin, bis {n} Bilder drauf sind oder du ihn entnimmst. Dann liegt er als Stapel im Fotostudio.": "The film stays in until it has {n} shots or you take it out. Then it's a stack in the photo studio.",
};
