// Kamera (Stufe 1, nur App) und der Calima-Look als Rezept in der Datei
export const CAMERA: Record<string, string> = {
  "Calima darf die Kamera nicht nutzen. Erlaube sie in den Einstellungen des iPhones unter Calima.": "Calima isn't allowed to use the camera. Allow it in the iPhone's Settings under Calima.",
  "Die Kamera lässt sich gerade nicht öffnen.": "The camera can't be opened right now.",
  "Das Foto ließ sich nicht aufnehmen. Versuch es noch einmal.": "The photo couldn't be taken. Try again.",
  "Loslassen bringt den Look zurück": "Let go to bring the look back",
  "Zoom {factor}": "Zoom {factor}",
  "Kamera öffnet …": "Opening camera …",
  Looks: "Looks",
  Auslösen: "Shutter",
  Rückkamera: "Back camera",
  Frontkamera: "Front camera",
  "{n} auf dem Stapel von heute. Einsortieren kannst du abends.": "{n} on today's stack. You can sort them in the evening.",
  "Halten zeigt das Original, Wischen macht heller oder dunkler.": "Hold to see the original, swipe to go brighter or darker.",
  "Calima-Look": "Calima look",
  "{label} „{name}“ mitgenommen. Liegt oben bei „Deine Looks“.": "{label} “{name}” taken along. It's up under “Your looks”.",
  "Aus der Datei gelesen, in Calima nachempfunden": "Read from the file, approximated in Calima",
  "Aus der Datei gelesen, so wie das Foto gesichert wurde": "Read from the file, just as the photo was saved",
  "So fotografieren": "Shoot like this",
  "Für die Kamera brauchst du ein Konto. Mitgenommen ist der Look trotzdem.": "The camera needs an account. The look is taken along anyway.",
  "Das Foto liegt auf dem Stapel von heute.": "The photo is on today's stack.",
  "Die {n} Fotos liegen auf dem Stapel von heute.": "The {n} photos are on today's stack.",
  "Der Film liegt im Fotostudio.": "The film is in the photo studio.",
  "Entwickelt. Das Bild liegt auf dem Stapel seines Tages.": "Developed. The picture is on the stack for its day.",
  "Entwickelt. Die {n} Bilder liegen auf dem Stapel ihres Tages.": "Developed. The {n} pictures are on the stack for their day.",
  "Entwickelt. Die Bilder liegen auf dem Stapel ihres Tages.": "Developed. The pictures are on the stack for their day.",
  "Calima-Look mitnehmen": "Take the Calima look along",
  "Farbe und Licht ohne Zuschnitt, so wie das Foto gesichert wurde.": "Colour and light without the crop, just as the photo was saved.",
  // Film einlegen (Stufe 2)
  "Film, {i} von {n}": "Film, {i} of {n}",
  "{i} von {n}": "{i} of {n}",
  "Film einlegen": "Load film",
  "Film raus": "Film out",
  "Die Bilder siehst du erst nach dem Entwickeln. Voll ist der Film bei {n}; beiseitegelegt wartet er auf dich.": "You'll see the pictures only once the film is developed. It's full at {n}; set aside, it waits for you.",
  Beiseitelegen: "Set aside",
  // Werkzeug (E1)
  Werkzeug: "Tools",
  "Werkzeug weglegen": "Put tools away",
  Zeit: "Shutter",
  ISO: "ISO",
  Fokus: "Focus",
  Weiß: "White",
  Räder: "Dials",
  Brennweite: "Focal length",
  "echtes Objektiv": "real lens",
  "Ausschnitt aus der Hauptkamera": "Crop from the main camera",
  "Raster und Wasserwaage": "Grid and level",
  "Rad auf A, die Kamera stellt selbst": "Dial to A, the camera decides",
  "Schärfe von Hand, mit Lupe": "Manual focus, with loupe",
  Farbtemperatur: "Color temperature",
  Belichtungsmesser: "Light meter",
  "Ziehen auf dem Lineal dreht das Rad. A gibt es der Kamera zurück.": "Drag the ruler to turn the dial. A hands it back to the camera.",
  "Letztes Foto ansehen": "View last photo",
  "Schärfe und Licht stehen fest. Ein Tipp auf die Marke löst sie.": "Focus and exposure are locked. Tap the mark to release.",
  "Noch ein Tipp auf die Marke hält Schärfe und Licht fest.": "Tap the mark again to lock focus and exposure.",
  "Links kälter, rechts wärmer, oben grüner, unten magenta. Doppeltipp gibt es der Kamera zurück.": "Left cooler, right warmer, up greener, down more magenta. Double-tap hands it back to the camera.",
  "Farbtemperatur und Tönung": "Color temperature and tint",
  grün: "green",
  magenta: "magenta",
  Fest: "Locked",
  "Letztes Foto": "Last photo",
  "Zurück zur Kamera": "Back to the camera",
  "{mm} mm ist ein Ausschnitt aus der Hauptkamera, kein eigenes Objektiv.": "{mm} mm is a crop from the main camera, not a lens of its own.",
  Entwickeln: "Develop",
  "Film „{name}“ weiter belichten, {i} von {n}": "Keep shooting film “{name}”, {i} of {n}",
  "{i}/{n}": "{i}/{n}",
};
