// Englisch für Bearbeiten (Foto entwickeln), Zuschnitt, Ausschnitt und den Rezeptzettel (siehe index.ts)

export const DEVELOP: Record<string, string> = {
  // Reiter und Gruppen
  Vorschläge: "Suggestions",
  Feinschliff: "Fine-tuning",
  Schwach: "Weak",
  "Licht genauer": "More light",
  "Lichter, Weiß, Schwarz, Klarheit": "Highlights, whites, blacks, clarity",
  "Farbe genauer": "More color",
  "Tönung, Dynamik": "Tint, vibrance",
  "Farben einzeln": "Individual colors",
  "acht Farbtöne": "eight hues",
  Vignette: "Vignette",
  "Ränder abdunkeln": "darken the edges",
  "Helligkeit Punkt für Punkt": "brightness point by point",
  Gerade: "Straight",
  "Mehr Kontrast": "More contrast",
  Weicher: "Softer",
  Matt: "Matte",
  angepasst: "adjusted",
  "{label} zurücksetzen": "Reset {label}",

  // Rezept: Weißabgleich
  "Weißabgleich-Verschiebung": "White balance shift",
  "rechts mehr Rot": "right: more red",
  "oben mehr Blau": "up: more blue",
  "Doppeltipp: Mitte": "Double-tap: center",
  Rot: "Red",
  Blau: "Blue",

  // Hinweise
  "Die kleinen Vorschauen ließen sich nicht laden ({reason}).": "The small previews couldn't be loaded ({reason}).",
  "Die Vorschau ließ sich nicht starten ({reason}).": "The preview couldn't start ({reason}).",
  "Keine klare Kante gefunden. Dreh am Rad, bis es passt.": "No clear edge found. Turn the dial until it looks right.",
  "Das Foto ist schon gerade.": "The photo is already straight.",
  "Um {angle} gerade gerichtet. Das Rad stellt nach.": "Straightened by {angle}. Use the dial to fine-tune.",
  "Auf alle {n}": "Apply to all {n}",
  "jedes mit eigenem Auto": "each with its own Auto",
  "Auf {n} Fotos, jedes mit eigenem Auto. Zuschnitt bleibt je Foto. Rückgängig nimmt es zurück.":
    "Applied to {n} photos, each with its own Auto. Each photo keeps its crop. Undo takes it back.",
  Angeglichen: "Matched",
  "{n} Fotos rücken zusammen": "{n} photos move closer together",
  "Die Fotos sind in Licht und Farbe zueinander gerückt. Rückgängig nimmt es zurück.":
    "The photos now match more closely in light and color. Undo takes it back.",
  "Foto übernimmt die Bearbeitung": "photo takes on the edit",
  "Fotos übernehmen die Bearbeitung": "photos take on the edit",
  "Auf 1 Foto gewischt, jedes mit eigenem Auto.": "Swiped onto 1 photo, with its own Auto.",
  "Auf {n} Fotos gewischt, jedes mit eigenem Auto.": "Swiped onto {n} photos, each with its own Auto.",
  "{name} · geändert": "{name} · changed",
  "Eigene Werte": "Custom values",
  "„{name}“ steht jetzt oben bei „Deine Looks“, auch für andere Fotos und Bücher.":
    "“{name}” is now at the top under “Your looks”, for other photos and books too.",
  "Der Look ließ sich nicht speichern.": "The look couldn't be saved.",
  "„{name}“ löschen? Fotos, die ihn nutzen, bleiben, wie sie sind.": "Delete “{name}”? Photos using it stay as they are.",
  Behalten: "Keep",
  "„{name}“ heißt schon ein anderer Look.": "Another look is already called “{name}”.",
  "Heißt jetzt „{name}“.": "Now called “{name}”.",
  "„{name}“ hat jetzt die Einstellungen dieses Fotos.": "“{name}” now has this photo's settings.",
  "Neuer Name für „{name}“": "New name for “{name}”",
  "„{name}“ steht nicht mehr da. Unter „Weitere“ holst du ihn zurück.": "“{name}” is gone. Bring it back under “More”.",
  "Fuji-Rezept": "Fuji recipe",
  "Lightroom-Werte": "Lightroom values",
  "Noch nichts zu kopieren: Stell zuerst Farbe oder Licht ein.": "Nothing to copy yet: adjust color or light first.",
  "Mitgenommen. Liegt oben bei „Deine Looks“, bei jedem Foto mit einem Tipp (⇧⌘V).":
    "Taken. It's at the top under “Your looks”, one tap away on every photo (⇧⌘V).",
  "{label} „{name}“ mitgenommen, in Calima nachempfunden. Liegt oben bei „Deine Looks“.":
    "{label} “{name}” taken, recreated in Calima. It's at the top under “Your looks”.",
  "„{name}“ steht jetzt bei „Deine Looks“. Umbenennen geht per Rechtsklick oder langem Drücken.":
    "“{name}” is now under “Your looks”. Right-click or long-press to rename it.",
  Original: "Original",
  "loslassen zeigt wieder bearbeitet": "let go to see the edit again",
  "Wischen stellt unter Looks und Feinschliff ein. Hier genügt ein Tipp auf einen Vorschlag.":
    "Swiping adjusts things under Looks and Fine-tuning. Here, just tap a suggestion.",
  "Im Rezept stellst du die Werte unten ein, wie an der Kamera.": "In Recipe, you set the values below, just like on the camera.",
  "Erst einen Look wählen, dann wischen.": "Pick a look first, then swipe.",
  "Änderungen verwerfen?": "Discard changes?",
  Verwerfen: "Discard",
  "Speichere Foto {i} von {n} …": "Saving photo {i} of {n} …",
  "Speichere das Foto …": "Saving the photo …",
  "Speichern hat nicht geklappt. Prüf die Verbindung und tipp noch einmal auf Fertig. ({reason})":
    "Saving didn't work. Check your connection and tap Done again. ({reason})",
  "Rahmen ziehen verschiebt ihn, Ecken ändern die Größe. Das Rad darunter richtet gerade. Die Seite schneidet im Rahmen zusätzlich zu.":
    "Drag the frame to move it, drag the corners to resize. The dial below straightens. The page crops further within the frame.",
  "Rahmen ziehen verschiebt ihn, Ecken ändern die Größe. Das Rad darunter richtet gerade.":
    "Drag the frame to move it, drag the corners to resize. The dial below straightens.",
  "Den Strich auf dem Foto ziehen. Links ist das Original.": "Drag the line on the photo. The original is on the left.",
  "Ein Foto einstellen, dann „Auf alle“. Oder sein Bild im Streifen über die anderen ziehen.":
    "Adjust one photo, then “Apply to all”. Or drag its thumbnail in the strip across the others.",
  "Ein Tipp genügt. Lange drücken oder Rechtsklick tauscht einen Vorschlag aus.": "One tap is enough. Long-press or right-click to swap a suggestion.",
  "Auf dem Foto wischen ändert die Stärke. Den Look noch einmal antippen oder „Ohne Look“ nimmt ihn weg.":
    "Swipe on the photo to change the strength. Tap the look again or “No look” to remove it.",
  "Jede Kachel zeigt den Look auf deinem Foto.": "Each tile shows the look on your photo.",
  "Die Einstellungen einer Fuji-Kamera, nachempfunden. Gilt auch für Fotos vom iPhone.":
    "The settings of a Fuji camera, recreated. Works for iPhone photos too.",
  "Auf dem Foto wischen stellt „{name}“ ein. ↺ setzt einen Regler zurück.": "Swipe on the photo to adjust “{name}”. ↺ resets a slider.",

  // Foto und Bühne
  "Fotos dieses Stapels": "Photos in this stack",
  "Fotos dieser Doppelseite": "Photos on this spread",
  "{name}, in Bearbeitung. Über die anderen ziehen überträgt die Bearbeitung": "{name}, being edited. Drag across the others to copy the edit",
  "{name}, in Bearbeitung": "{name}, being edited",
  "{name} bearbeiten": "Edit {name}",
  "Foto bearbeiten": "Edit photo",
  "{name}. Halten zeigt das Original, waagerecht wischen stellt ein, zwei Finger oder Doppeltipp zoomen.":
    "{name}. Hold to see the original, swipe sideways to adjust, pinch or double-tap to zoom.",
  "{name}, bearbeitet. Halten zeigt das Original, waagerecht wischen stellt ein, zwei Finger oder Doppeltipp zoomen.":
    "{name}, edited. Hold to see the original, swipe sideways to adjust, pinch or double-tap to zoom.",
  "Das Foto ließ sich nicht laden.": "The photo couldn't be loaded.",
  "Noch einmal laden": "Load again",
  vorher: "before",
  nachher: "after",
  ", ganzes Foto zeigen": ", show whole photo",
  "Auch: Taste C": "Also: C key",
  ", zugeschnitten": ", cropped",
  "Auch: M oder \\ gedrückt halten zeigt das Original, 1–4 wechseln die Reiter": "Also: hold M or \\ to see the original, 1–4 switch tabs",
  "Vorher / nachher": "Before / after",
  "Foto zurücksetzen": "Reset photo",
  "Auch: Doppelklick oder Mausrad aufs Foto, + und − auf der Tastatur, 0 zeigt das ganze Foto":
    "Also: double-click or scroll on the photo, + and − on the keyboard, 0 shows the whole photo",
  "Du bearbeitest": "You're editing",
  "Ein anderes Foto antippen wechselt.": "Tap another photo to switch.",
  Zurücksetzen: "Reset",
  Format: "Format",
  Hoch: "Portrait",
  Quer: "Landscape",
  Geraderichten: "Straighten",
  "Werkzeuge zeigen": "Show tools",
  "Werkzeuge einklappen, Foto ganz zeigen": "Collapse tools, show the full photo",

  // Vorschläge und Looks
  Angleichen: "Match",
  "Deine Looks": "Your looks",
  "für alle Fotos und Bücher": "for all photos and books",
  "Zu deinen Looks": "Add to your looks",
  "Aus „Zuletzt“ entfernen": "Remove from “Recent”",
  mitgenommen: "taken",
  Umbenennen: "Rename",
  "nimmt Farbe und Licht von jetzt": "uses the current color and light",
  "Mit diesem Foto überschreiben": "Overwrite with this photo",
  "eigener Look": "your look",
  "eigenes Rezept": "your recipe",
  "{name} löschen": "Delete {name}",
  "aus diesem Buch": "from this book",
  "Licht und Farbe automatisch": "Automatic light and color",
  "Austauschen gegen": "Swap for",
  Entfernen: "Remove",
  "Vorschläge wie anfangs": "Reset suggestions",
  Weitere: "More",
  "Vorschläge dazuholen, lange drücken tauscht": "Add suggestions, long-press to swap",
  Dazuholen: "Add",
  "an die Nachbarfotos": "to the neighboring photos",
  "braucht ein zweites Foto auf der Seite": "needs a second photo on the page",
  "Stimmung übernehmen": "Borrow the mood",
  "vom {name}": "from {name}",
  "Noch keine. Stell ein Foto ein, wie es dir gefällt, und speichere es als Look für alle Fotos und Bücher.":
    "None yet. Adjust a photo the way you like it and save it as a look for all photos and books.",
  "Als eigenen Look speichern": "Save as your own look",
  "Farbe und Licht ohne Zuschnitt, für die anderen Fotos, ⇧⌘C": "Color and light without the crop, for the other photos, ⇧⌘C",
  "Für andere Fotos mitnehmen": "Take for other photos",
  "Ohne Look": "No look",
  "nimmt den Look weg": "removes the look",
  "Stärke {name}": "Strength {name}",

  // Mehr Werkzeuge
  "{name} schließen": "Close {name}",
  Vorlagen: "Presets",
  "Auf die Fläche klicken setzt einen Punkt. Aus der Fläche ziehen oder doppelklicken nimmt ihn weg.":
    "Click the area to add a point. Drag it out or double-click to remove it.",
  Farbton: "Hue",
  Sättigung: "Saturation",
  Helligkeit: "Luminance",
  "Mehr Werkzeuge": "More tools",
  "{n} von {m} offen": "{n} of {m} open",
  "Lichter, Klarheit, Farben, Vignette, Kurve": "Highlights, clarity, colors, vignette, curve",
  "Lichter, Klarheit, Farben, Vignette": "Highlights, clarity, colors, vignette",

  // Rezept
  "Ohne Rezept": "No recipe",
  "Als eigenen Look speichern …": "Save as your own look …",
  Ohne: "None",
  "Ton und Farbe": "Tone and color",
  Lichter: "Highlights",
  Schatten: "Shadows",
  "Color Chrome FX Blau": "Color Chrome FX Blue",
  Korngröße: "Grain size",
  Klein: "Small",
  "Name für deinen Look": "Name for your look",
  Speichern: "Save",

  // Zuschnitt
  Frei: "Free",
  zugeschnitten: "cropped",
  "zugeschnitten {ratio}": "cropped {ratio}",
  "gerade {angle}": "straightened {angle}",
  "{deg}° gedreht": "rotated {deg}°",
  gespiegelt: "flipped",

  // Farbtöne
  "Lippen, Mohn, Rücklichter": "Lips, poppies, tail lights",
  Orange: "Orange",
  "Haut, Sand, Abendlicht": "Skin, sand, evening light",
  Gelb: "Yellow",
  "Laub im Herbst, Raps, Kerzenlicht": "Autumn leaves, rapeseed, candlelight",
  Grün: "Green",
  "Wiesen, Blätter": "Meadows, leaves",
  Türkis: "Turquoise",
  "Lagunen, Glas": "Lagoons, glass",
  "Himmel, Meer, Schatten": "Sky, sea, shadows",
  Lila: "Purple",
  "Lavendel, Dämmerung": "Lavender, dusk",
  Magenta: "Magenta",
  "Blüten, Neon": "Blossoms, neon",

  // Looks
  Sommer: "Summer",
  "warm, Schwarz leicht offen": "warm, slightly lifted blacks",
  Kreide: "Chalk",
  "matt und blass": "matte and pale",
  Dämmerung: "Dusk",
  "kühle Tiefen, warme Lichter": "cool shadows, warm highlights",
  Salz: "Salt",
  "kühl und klar": "cool and clear",
  Kohle: "Charcoal",
  "Schwarzweiß mit Rotfilter": "black and white with red filter",
  Messing: "Brass",
  "kräftig wie Diafilm, gedämpftes Grün": "punchy like slide film, muted greens",

  // Voreingestellte Rezepte
  Sommerlicht: "Summer light",
  "warm, weiche Lichter": "warm, soft highlights",
  Nachmittag: "Afternoon",
  "satt, kühle Tiefen": "rich, cool shadows",
  Kalkwand: "Whitewash",
  "golden, harte Sonne": "golden, harsh sun",
  Hafen: "Harbor",
  "kühl, tiefes Blau": "cool, deep blue",
  "Schwarzweiß, kräftig": "black and white, punchy",

  // Fertige Vorschläge
  Klar: "Crisp",
  "frisch, kräftig, knackig": "fresh, punchy, sharp",
  "Warmer Film": "Warm film",
  "weich und warm, wie analog": "soft and warm, like analog",
  Schwarzweiß: "Black and white",
  "kräftiger Kontrast, dunkle Ränder": "strong contrast, dark edges",
  "blass, Schwarz offen": "pale, lifted blacks",
  Abendlicht: "Evening light",
  "golden, weiche Schatten": "golden, soft shadows",
  Kühl: "Cool",
  "klar und frisch, wie Meerluft": "clear and fresh, like sea air",
  Diafilm: "Slide film",
  "satt und kräftig": "rich and punchy",
  Weich: "Soft",
  "hell und sanft, für Gesichter": "bright and gentle, for faces",

  // Zettel: was bearbeitet wurde
  "an die anderen Fotos angeglichen": "matched to the other photos",
  "Stimmung von {name}": "mood from {name}",
  "Stimmung übernommen": "mood borrowed",
  "fertiger Vorschlag": "ready-made suggestion",
  "{name}, angepasst": "{name}, adjusted",
  "eigene Werte": "custom values",
  groß: "large",
  klein: "small",
  Licht: "Light",
  Kontrast: "Contrast",
  "Schatten aufhellen": "Lift shadows",
  Wärme: "Warmth",
  Tönung: "Tint",
  Klarheit: "Clarity",

  // Einstellungen mitnehmen
  "Kopierte Einstellungen": "Copied settings",
  "Filmsimulation {film}": "Film simulation {film}",
  "Sepia-Ton": "Sepia tone",
  Farbfilter: "Color filter",
  "Weißabgleich {mode}": "White balance {mode}",
  Schärfe: "Sharpness",
  Rauschminderung: "Noise reduction",
  "Dunst entfernen": "Dehaze",
  "Color Grading": "Color grading",
  "Weißabgleich in Kelvin": "White balance in Kelvin",
  "Kurven je Farbkanal": "Per-channel curves",
  Doppelseite: "Spread",
  "Look von {label} {n}": "Look from {label} {n}",
  "Look aus diesem Buch": "Look from this book",

  // Ausschnitt im Bildfeld
  "Das Gesicht ist angeschnitten.": "The face is cut off.",
  "Das Hauptmotiv liegt am Rand oder ist angeschnitten.": "The main subject is at the edge or cut off.",
  "Das Gesicht liegt im Falz.": "The face is in the fold.",
  "Das Hauptmotiv liegt im Falz.": "The main subject is in the fold.",
  "Ausschnitt verschieben: Pfeiltasten, mit Umschalt in großen Schritten": "Move the crop: arrow keys, with Shift in bigger steps",
  "Punkt: erkanntes Gesicht. Ziehen oder Pfeiltasten verschieben den Ausschnitt.": "Dot: detected face. Drag or use the arrow keys to move the crop.",
  "Punkt: geschätztes Hauptmotiv. Ziehen oder Pfeiltasten verschieben den Ausschnitt.":
    "Dot: estimated main subject. Drag or use the arrow keys to move the crop.",
  "Ziehen oder Pfeiltasten verschieben den Ausschnitt.": "Drag or use the arrow keys to move the crop.",
  "Motiv in die Mitte": "Center the subject",
  "Feld füllen": "Fill the frame",
  "Ganzes Foto zeigen": "Show whole photo",

  // Rahmen und Drehrad
  "Rahmen. Ziehen verschiebt, Ecken ändern die Größe. Pfeiltasten verschieben.": "Frame. Drag to move, corners resize. Arrow keys move it.",
  "90° nach links drehen": "Rotate 90° left",
  "Horizont suchen und gerade richten": "Find the horizon and straighten",
  ": gerade richten": ": straighten",
  Spiegeln: "Flip",

  // Rezeptzettel
  Belichtungskorrektur: "Exposure compensation",
  "Fertig. Auf C1 gespeichert?": "Done. Saved to C1?",
  "Zurück zum Rezept": "Back to the recipe",
  "An der Kamera einstellen": "Set it on the camera",
  "Preset gesichert.": "Preset saved.",
  "Lade Preset …": "Loading preset …",
  "Farbmischer, Sättigung": "Color mixer, saturation",
  "Als Lightroom-Preset sichern …": "Save as Lightroom preset …",
  "Preset sichern (.xmp)": "Save preset (.xmp)",
  Gerät: "Device",
  Brennweite: "Focal length",
  "{mm} mm (KB)": "{mm} mm (35mm equiv.)",
  Blende: "Aperture",
  Zeit: "Shutter",
  Belichtung: "Exposure",
  Datum: "Date",
  "Nachbearbeitet in Calima (nachempfunden)": "Edited in Calima (recreated)",
  "Mitgenommen. Liegt im Fotostudio oben bei „Deine Looks“, und in der Werkbank unter „Look übernehmen“.":
    "Taken. It's at the top under “Your looks” in the Photo studio, and under “Apply look” on the Workbench.",
  "Speichere …": "Saving …",
  "Zum Speichern als Look brauchst du ein Konto. Mitgenommen ist es trotzdem.": "You need an account to save it as a look. It's taken anyway.",
  "„{name}“ liegt jetzt in deinen Looks.": "“{name}” is now in your looks.",
  "Der Look ließ sich nicht speichern. Mitgenommen ist er trotzdem.": "The look couldn't be saved. It's taken anyway.",
  "Für eigene Fotos mitnehmen": "Take for your own photos",
  "Bearbeitung mitnehmen": "Take the edit",
  "Als Look speichern": "Save as look",
  "Farbe und Licht ohne Zuschnitt. Das Rezept wird in Calima nachempfunden, nicht exakt.":
    "Color and light without the crop. The recipe is recreated in Calima, not exactly.",
  "Farbe und Licht ohne Zuschnitt. Das Preset wird in Calima nachempfunden, nicht exakt.":
    "Color and light without the crop. The preset is recreated in Calima, not exactly.",
  "Farbe und Licht ohne Zuschnitt, für deine eigenen Fotos.": "Color and light without the crop, for your own photos.",
  "Nicht übertragbar: {list}.": "Can't be carried over: {list}.",
  "Lightroom-Preset": "Lightroom preset",
  Kamera: "Camera",
  Bearbeitung: "Edits",
  Nachbearbeitet: "Edited",
  "{kind} zu {plate}": "{kind} for {plate}",
  "Tafel {n}": "Plate {n}",
  "Platzhalter: Die echten Werte kommen aus den Originaldateien der Kamera.": "Placeholder: the real values come from the camera's original files.",
  "Beispiel-Preset für den Prototyp, nicht die Bearbeitung dieses Fotos.": "Sample preset for the prototype, not this photo's edit.",

  // Fuji: Filmsimulationen und Weißabgleich (Namen wie im englischen Kameramenü)
  Monochrom: "Monochrome",
  "Monochrom + Rotfilter": "Monochrome + R filter",
  "Monochrom + Gelbfilter": "Monochrome + Ye filter",
  "Monochrom + Grünfilter": "Monochrome + G filter",
  "Acros + Rotfilter": "Acros + R filter",
  "Acros + Gelbfilter": "Acros + Ye filter",
  "Acros + Grünfilter": "Acros + G filter",
  "Auto, Weiß": "Auto, white priority",
  "Auto, Ambiente": "Auto, ambience priority",
  Tageslicht: "Daylight",
  Bewölkt: "Shade",
  "Leuchtstoff Tageslicht": "Fluorescent daylight",
  "Leuchtstoff Tagesweiß": "Fluorescent day white",
  "Leuchtstoff Kaltweiß": "Fluorescent cool white",
  "Leuchtstoff Warmweiß": "Fluorescent warm white",
  Kunstlicht: "Incandescent",
  Blitz: "Flash",
  Unterwasser: "Underwater",
  Eigener: "Custom",
  "Auto bis 3200": "Auto up to 3200",
  "Auto bis 6400": "Auto up to 6400",
  "Auto bis 1600": "Auto up to 1600",

  // Lightroom
  Tiefen: "Shadows",
  Struktur: "Texture",
  Aquamarin: "Aqua",
  Löschen: "Delete",
  Dynamik: "Vibrance",
  Ausrichtung: "Orientation",
};
