// Abendstapel: tagsüber auf den Stapel des Tages fotografieren, abends einsortieren, der Tag kommt ins Buch
// Abendstapel = evening stack · einsortieren = sort in · Tagebuch = journal · Reisetagebuch = travel journal
export const EVENING: Record<string, string> = {
  Reisetagebuch: "Travel journal",
  Tagebuch: "Journal",
  Waldtagebuch: "Forest journal",
  "Der Tag liegt im Buch": "The day is in the book",
  "Fertig für heute": "Done for today",
  Einsortieren: "Sort in",
  "Später weiter": "Continue later",
  "Fotos aus der Mediathek dazulegen …": "Add photos from your library …",
  "Alle im Fotostudio bearbeiten": "Edit all in the Photo studio",
  Weglegen: "Put aside",
  "Einen Satz dazu": "Add a line",
  "Nach rechts ins Buch, nach links weg. Antippen für einen Satz.": "Right into the book, left to put aside. Tap to add a line.",
  "Foto: {line}": "Photo: {line}",
  "Ein Satz zu diesem Foto": "A line about this photo",
  "Ramen mit Ei. Wieder hin.": "Ramen with egg. Going back.",
  "Wie war der Tag?": "How was the day?",
  "Früh los, Nebel am See. Abends Ramen.": "Early start, mist on the lake. Ramen at night.",
  "Steht auf der Tagesseite. Leer lassen geht auch.": "Goes on the day's page. Leaving it empty is fine.",
  "Seite gestalten": "Design the page",
  "Heute kommt nichts ins Buch.": "Nothing goes into the book today.",
  "Was du weggelegt hast, liegt noch eine Woche unter dem Pult. Dort holst du es zurück, danach räumt Calima es weg.":
    "What you put aside stays under the desk for a week. You can bring it back there; after that Calima clears it away.",
  "In „{title}“ legen": "Add to “{title}”",
  "{kind} anlegen": "Start “{kind}”",
  "Ein Foto kommt ins Buch.": "One photo goes into the book.",
  "{n} Fotos kommen ins Buch.": "{n} photos go into the book.",
  "Eins hast du weggelegt, es liegt noch eine Woche unter dem Pult.": "You put one aside; it stays under the desk for a week.",
  "{n} hast du weggelegt, sie liegen noch eine Woche unter dem Pult.": "You put {n} aside; they stay under the desk for a week.",
  "Ein Foto ist weggelegt, nach einer Woche räumt Calima es weg.": "One photo is put aside; Calima clears it away after a week.",
  "{n} Fotos sind weggelegt, nach einer Woche räumt Calima sie weg.": "{n} photos are put aside; Calima clears them away after a week.",
  "Zuletzt dein Tagebuch": "Your journal last time",
  "Neues Tagebuch": "New journal",
  "Der Tag kommt hinten dazu.": "The day goes at the end.",
  "Anderes Buch": "Other book",
  "Dein erstes Tagebuch. Calima schlägt vor:": "Your first journal. Calima suggests:",
  Buchart: "Kind of book",
  "Lieber in ein Buch, das es schon gibt": "Rather into a book you already have",
  "Lege Foto {i} von {n} …": "Adding photo {i} of {n} …",
  "Lädt hoch. Lass Calima dabei offen.": "Uploading. Keep Calima open meanwhile.",
  "Ein Foto liegt in „{title}“.": "One photo is in “{title}”.",
  "{n} Fotos liegen in „{title}“.": "{n} photos are in “{title}”.",
  "Ein Tag öffnet sich zum Einsortieren: nach rechts ins Buch, nach links weg. Nichts davon wird hochgeladen, bevor es im Buch liegt.":
    "A day opens for sorting: right into the book, left to put aside. Nothing is uploaded until it's in the book.",
  "{day}: {n} Fotos, {open} noch nicht einsortiert. Einsortieren": "{day}: {n} photos, {open} not sorted yet. Sort in",
  "{day}: {n} Fotos, alle einsortiert. Ins Buch legen": "{day}: {n} photos, all sorted. Put into the book",
  Heute: "Today",
  Gestern: "Yesterday",
  Fotografieren: "Take photos",
  "Das Foto liegt nicht mehr auf diesem Gerät.": "This photo is no longer on this device.",
};
