// Abendstapel: tagsüber auf den Stapel des Tages fotografieren, abends einsortieren, der Tag kommt ins Buch
// Abendstapel = evening stack · einsortieren = sort in · Tagebuch = journal · Reisetagebuch = travel journal
export const EVENING: Record<string, string> = {
  Reisetagebuch: "Travel journal",
  Tagebuch: "Journal",
  Waldtagebuch: "Forest journal",
  "Der Tag liegt im Buch": "The day is in the book",
  "Fertig für heute": "Done for today",
  Einsortieren: "Sort in",
  "Später weiter": "Continue later",
  "Fotos aus der Mediathek dazulegen …": "Add photos from your library …",
  "Alle im Fotostudio bearbeiten": "Edit all in the Photo studio",
  Weglegen: "Put aside",
  "Einen Satz dazu": "Add a line",
  "Nach rechts ins Buch, nach links weg. Antippen für einen Satz.": "Right into the book, left to put aside. Tap to add a line.",
  "Foto: {line}": "Photo: {line}",
  "Ein Satz zu diesem Foto": "A line about this photo",
  "Ramen mit Ei. Wieder hin.": "Ramen with egg. Going back.",
  "Heute kommt nichts ins Buch.": "Nothing goes into the book today.",
  "Die weggelegten Fotos verschwinden vom Pult. Was nur Calima fotografiert hat, ist dann weg. Rückgängig oben holt das letzte zurück.":
    "The photos you put aside leave the desk. Anything only Calima took is then gone. Undo at the top brings back the last one.",
  "Das Foto wegräumen": "Clear away the photo",
  "Die {n} Fotos wegräumen": "Clear away the {n} photos",
  "In „{title}“ legen": "Add to “{title}”",
  "{kind} anlegen": "Start “{kind}”",
  "Ein Foto kommt ins Buch.": "One photo goes into the book.",
  "{n} Fotos kommen ins Buch.": "{n} photos go into the book.",
  "Eins legst du weg, es verschwindet danach vom Pult.": "You're putting one aside; it leaves the desk afterwards.",
  "{n} legst du weg, sie verschwinden danach vom Pult.": "You're putting {n} aside; they leave the desk afterwards.",
  "Zuletzt dein Tagebuch": "Your journal last time",
  "Neues Tagebuch": "New journal",
  "Der Tag kommt hinten dazu.": "The day goes at the end.",
  "Anderes Buch": "Other book",
  "Dein erstes Tagebuch. Calima schlägt vor:": "Your first journal. Calima suggests:",
  Buchart: "Kind of book",
  "Lieber in ein Buch, das es schon gibt": "Rather into a book you already have",
  "Lege Foto {i} von {n} …": "Adding photo {i} of {n} …",
  "Lädt hoch. Lass Calima dabei offen.": "Uploading. Keep Calima open meanwhile.",
  "Ein Foto liegt in „{title}“.": "One photo is in “{title}”.",
  "{n} Fotos liegen in „{title}“.": "{n} photos are in “{title}”.",
  "Ein Tag öffnet sich zum Einsortieren: nach rechts ins Buch, nach links weg. Nichts davon wird hochgeladen, bevor es im Buch liegt.":
    "A day opens for sorting: right into the book, left to put aside. Nothing is uploaded until it's in the book.",
  "{day}: {n} Fotos, {open} noch nicht einsortiert. Einsortieren": "{day}: {n} photos, {open} not sorted yet. Sort in",
  "{day}: {n} Fotos, alle einsortiert. Ins Buch legen": "{day}: {n} photos, all sorted. Put into the book",
  Heute: "Today",
  Gestern: "Yesterday",
  Fotografieren: "Take photos",
  "Das Foto liegt nicht mehr auf diesem Gerät.": "This photo is no longer on this device.",
};
