// Englisch für Bücherzimmer, Buch, Gastlink, Profil und die Bausteine dazu (siehe index.ts)

export const LIBRARY: Record<string, string> = {
  // Bausteine
  ", offen": ", open",
  Hinweise: "Notifications",
  Profil: "Profile",
  "Mit dem Anmelden gelten die": "By signing in you agree to the",
  "Kostenlos. Mit dem Anmelden gelten die": "Free. By signing in you agree to the",
  "Deine Fotos, gebunden.": "Your photos, bound.",
  "Ein paar Fotos werden ein Buch, das man wirklich umblättert. Freunde lesen per Link, ohne Konto.":
    "A few photos become a book you actually leaf through. Friends read it via a link, no account needed.",

  // Bücher aus dem Editor (store.ts)
  Ringelblume: "Marigold",
  Nebel: "Mist",
  Salbei: "Sage",
  Sand: "Sand",
  Ziegel: "Brick",
  Meer: "Sea",
  "Eine Fotografie": "One photograph",
  "{n} Fotografien": "{n} photographs",
  "Ohne Titel": "Untitled",
  "Fotografie: {name}": "Photography: {name}",
  "Gebunden mit Calima.": "Bound with Calima.",
  "Foto {no} von {n}": "Photo {no} of {n}",
  "Die Datei ist zu groß für eine Calima-Buchdatei.": "This file is too large for a Calima book file.",
  "Zum Löschen brauchst du eine Verbindung.": "You need a connection to delete.",
  Bücher: "Books",
  "Geteilte Links": "Shared links",
  "Ablage und Rezepte": "Tray and recipes",
  Fotos: "Photos",
  "Anstößig oder sexuell": "Offensive or sexual",
  "Gewalt oder Hass": "Violence or hate",
  "Belästigung oder Bedrohung": "Harassment or threats",
  "Fremde Fotos, ohne Einverständnis": "Someone else's photos, without consent",
  "Etwas anderes": "Something else",
  Gast: "Guest",

  // Buch
  "Sechsundzwanzig Fotografien": "Twenty-six photographs",
  "Vierzehn Fotografien": "Fourteen photographs",
  "Fünf Fotografien": "Five photographs",
  "Tafel {no}: {title}": "Plate {no}: {title}",
  "Tafel {no}": "Plate {no}",
  "Tafel {from}–{to}": "Plates {from}–{to}",
  Einband: "Cover",
  Titel: "Title",
  Verzeichnis: "Index",
  Kolophon: "Colophon",
  Rezept: "Recipe",
  Kamera: "Camera",
  Bearbeitung: "Edits",
  "Fotobuch {title}": "Photo book {title}",
  "Calima, zurück zum Tisch": "Calima, back to the table",
  Bearbeiten: "Edit",
  "Bearbeiten (oder lange aufs Buch drücken)": "Edit (or press and hold the book)",
  "Oder lange aufs Buch drücken": "Or press and hold the book",
  "Eselsohr bei Tafel {no}": "Dog-ear on plate {no}",
  "Ecke gedrückt halten": "Press and hold the corner",
  Zurückblättern: "Previous page",
  Weiterblättern: "Next page",
  Bildfolge: "Sequence",
  "Wischen oder Tippen zum Blättern": "Swipe or tap to turn the pages",
  "Scrollen, Klicken oder ← → zum Blättern": "Scroll, click or ← → to turn the pages",
  "Scrollen oder Wischen zum Blättern": "Scroll or swipe to turn the pages",
  "{label} zu {plate}": "{label} for {plate}",

  // Laden
  "Bücherzimmer wird geladen": "Loading your library",
  "Moment,": "One sec,",
  "ich hol deine": "getting your",
  "Bücher.": "books.",
  "dauert heut": "slow today",
  "kein Netz?": "no signal?",

  // Karussell
  Karussell: "carousel",
  "Voriges Buch": "Previous book",
  "Nächstes Buch": "Next book",
  "Neues Buch": "New book",
  "{title}, {i} von {n}": "{title}, {i} of {n}",

  // Bücherzimmer
  "Keine Bücher": "No books",
  "Ein Buch": "One book",
  "{n} Bücher": "{n} books",
  eines: "one",
  "Dein Bücherzimmer": "Your library",
  "Hier liegen deine eigenen Fotobücher und die, die Freunde für dich hingelegt haben.": "Here are your own photo books and the ones friends have handed over to you.",
  "Von dir": "From you",
  "Für dich": "For you",
  "Konnte deine Bücher nicht laden: {error}": "Couldn't load your books: {error}",
  "Konnte die Bücher von Freunden nicht laden: {error}": "Couldn't load your friends' books: {error}",
  "Nochmal versuchen": "Try again",
  "Neues Buch anlegen": "Start a new book",
  Neues: "New",
  Buch: "Book",
  "Fotos wählen, fertig.": "Choose photos, done.",
  "Fotos reinziehen, fertig.": "Drop photos in, done.",
  "Fotos wählen": "Choose photos",
  "Aus Datei öffnen": "Open from file",
  "{n} Tafeln · mitgeliefert": "{n} plates · included",
  "Beispiel · {n} Tafeln von Michel Leotta": "Sample · {n} plates by Michel Leotta",
  "So sieht ein fertiges Buch aus. Blätter rein, dann mach dein eigenes.": "This is what a finished book looks like. Leaf through, then make your own.",
  Mehr: "More",
  "„{title}“ liegt nicht mehr in deinem Zimmer.": "“{title}” is no longer in your library.",
  "Aus dem Zimmer nehmen": "Remove from library",
  "{n} Tafeln": "{n} plates",
  "{n} Fotos · ohne Titel": "{n} photos · untitled",
  "Hinlegen für …": "Hand over to …",
  "„{title}“ liegt im Papierkorb.": "“{title}” is in the trash.",
  "In den Papierkorb": "Move to trash",
  "von {name}": "from {name}",
  "von {name} · {n} Tafeln": "from {name} · {n} plates",
  "Melden …": "Report …",
  "Bücher von {name} ausblenden": "Hide books from {name}",
  "Bücher, die dir jemand hinlegt, landen von selbst hier, sobald du ihren Link öffnest.": "Books someone hands over to you land here on their own as soon as you open their link.",
  Weggelegt: "Put away",
  Mitgeliefert: "Included",
  Beispiel: "Sample",
  "{title} zurücklegen": "Put {title} back",
  Papierkorb: "Trash",
  "Papierkorb ({n})": "Trash ({n})",
  "Bücher im Papierkorb liegen nirgends aus, ihre geteilten Links zeigen nichts mehr.": "Books in the trash aren't shown anywhere, and their shared links show nothing.",
  "Papierkorb leeren …": "Empty trash …",
  "Papierkorb leeren": "Empty trash",
  "Ein Buch wird endgültig gelöscht: mit allen Fotos, Zwischenständen und geteilten Links samt Zetteln der Gäste. Das lässt sich nicht rückgängig machen.":
    "One book will be deleted for good: with all its photos, saved versions and shared links, including guests' notes. This can't be undone.",
  "{n} Bücher werden endgültig gelöscht: mit allen Fotos, Zwischenständen und geteilten Links samt Zetteln der Gäste. Das lässt sich nicht rückgängig machen.":
    "{n} books will be deleted for good: with all their photos, saved versions and shared links, including guests' notes. This can't be undone.",
  "Löscht …": "Deleting …",
  "Endgültig löschen": "Delete for good",
  Abbrechen: "Cancel",
  Rückgängig: "Undo",
  "liegt noch bei niemandem": "not handed over to anyone yet",
  "bei {names}": "with {names}",
  und: "and",
  "Ein Foto": "One photo",
  "{n} Fotos": "{n} photos",
  "1 Zettel": "1 note",
  "{n} Zettel": "{n} notes",
  "1 Eselsohr": "1 dog-ear",
  "{n} Eselsohren": "{n} dog-ears",
  Aufschlagen: "Open",
  "Noch nichts zurück. Zettel und Eselsohren landen hier.": "Nothing back yet. Notes and dog-ears land here.",
  "{n} neu": "{n} new",
  Alle: "All",
  "Zettel von {who}: {text}. Alle Rückmeldungen ansehen": "Note from {who}: {text}. See all responses",
  "{who} hat Tafel {no} geknickt. Dort aufschlagen": "{who} dog-eared plate {no}. Open there",
  "{who} hat Tafel {no} geknickt": "{who} dog-eared plate {no}",
  "{who} hat Ecken geknickt": "{who} dog-eared some corners",
  "{who} haben Ecken geknickt": "{who} dog-eared some corners",
  "Zurück von Freunden: {title}": "Back from friends: {title}",
  "Zettel und Eselsohren": "Notes and dog-ears",
  "Buch aufschlagen": "Open book",
  "Links und Zettel verwalten …": "Manage links and notes …",
  "hat {plate} geknickt": "dog-eared {plate}",
  "eine Tafel": "a plate",
  "{when} · dort aufschlagen": "{when} · open there",
  "Dort aufschlagen": "Open there",
  "1 neuer Zettel": "1 new note",
  "{n} neue Zettel": "{n} new notes",
  "1 neues Eselsohr": "1 new dog-ear",
  "{n} neue Eselsohren": "{n} new dog-ears",
  "{what} bei {title}": "{what} in {title}",
  "{what} in {n} Büchern": "{what} in {n} books",
  "Noch liegt hier nichts. Leg dein erstes Buch an.": "Nothing here yet. Start your first book.",
  "{books} von dir.": "{books} from you.",
  "{books} für dich.": "{books} for you.",
  "{books}: {mine} von dir, {given} für dich.": "{books}: {mine} from you, {given} for you.",

  // Gastlink
  "Dieser Link ist unvollständig.": "This link is incomplete.",
  "Keine Verbindung. Das Buch lädt, sobald du wieder online bist.": "No connection. The book will load as soon as you're back online.",
  "Dieses Buch liegt hier nicht mehr. Vielleicht wurde der Link zurückgezogen.": "This book isn't here anymore. Maybe the link was withdrawn.",
  "Bücher von {name} hast du ausgeblendet. Im Profil kannst du das zurücknehmen.": "You've hidden books from {name}. You can undo that in your profile.",
  "Ein Buch für {name}": "A book for {name}",
  "Liegt in deinem Bücherzimmer": "In your library",
  "In mein Bücherzimmer legen": "Add to my library",
  Behalten: "Keep",
  "Für {to}, von {from}": "For {to}, from {from}",
  "In dein Bücherzimmer legen": "Add to your library",
  "Mit einem Konto liegt „{title}“ in deinem Bücherzimmer unter „Für dich“, und du kannst eigene Bücher machen.":
    "With an account, “{title}” sits in your library under “For you”, and you can make books of your own.",
  "dieses Buch": "this book",
  "Es gelten die": "Subject to the",
  "Buch melden": "Report book",
  "Zum Bücherzimmer": "To your library",
  "Zu Calima": "To Calima",
  "Zur Startseite": "To the home page",

  // Zettel und Eselsohren
  "Das Eselsohr ist nicht angekommen. Versuch es bitte nochmal.": "The dog-ear didn't arrive. Please try again.",
  "So etwas gehört nicht auf einen Zettel. Formulier es bitte anders.": "That doesn't belong on a note. Please put it differently.",
  "Der Zettel ist nicht angekommen. Versuch es bitte nochmal.": "The note didn't arrive. Please try again.",
  "Dein Zettel hängt bei {name} an dieser Stelle.": "Your note is pinned here for {name}.",
  "Eselsohr bei {name}": "Dog-ear sent to {name}",
  Zettel: "Note",

  // Hinlegen für …
  "Der Link ließ sich nicht anlegen. Prüf die Verbindung und tipp noch einmal.": "Couldn't create the link. Check your connection and tap again.",
  "Ich hab dir ein Fotobuch hingelegt: „{title}“. Zum Blättern, ohne Konto.": "I've handed you a photo book: “{title}”. To leaf through, no account needed.",
  "Link für {name} ist unterwegs.": "Link for {name} is on its way.",
  "Kopieren hat nicht geklappt. Tipp auf Teilen und wähl dort Kopieren.": "Copying didn't work. Tap Share and choose Copy there.",
  "Link für {name} kopiert.": "Link for {name} copied.",
  "Buch hinlegen": "Hand over book",
  "„{title}“ hinlegen": "Hand over “{title}”",
  "Jede Person bekommt einen eigenen Link, ohne Konto. Wer den Link hat, kann das Buch ansehen, und sonst nichts. Du kannst ihn jederzeit zurückziehen.":
    "Each person gets their own link, no account needed. Whoever has the link can view the book, and nothing else. You can withdraw it any time.",
  "Titel des Buchs": "Book title",
  "Steht auf dem Einband": "Goes on the cover",
  "Für wen?": "For whom?",
  "Link erstellen": "Create link",
  "Ich teile nur, woran ich die Rechte habe, und halte mich an die": "I only share what I have the rights to, and I follow the",
  "Lade …": "Loading …",
  "Für {name}": "For {name}",
  "Wird zurückgezogen": "Withdrawing",
  "1 Rückmeldung": "1 response",
  "{n} Rückmeldungen": "{n} responses",
  "Liegt bereit": "Ready",
  "Link für {name} behalten": "Keep link for {name}",
  "Link für {name} teilen": "Share link for {name}",
  Kopiert: "Copied",
  "Link für {name} kopieren": "Copy link for {name}",
  "Link für {name} zurückziehen": "Withdraw link for {name}",
  "{from} · Link für {name}": "{from} · link for {name}",
  "Eselsohr bei Tafel {no} entfernen": "Remove dog-ear on plate {no}",
  "Zettel von {name} entfernen": "Remove note from {name}",

  // Melden
  "Danke. Ich sehe mir das innerhalb von 24 Stunden an und nehme das Buch herunter, wenn es gegen die Nutzungsbedingungen verstößt.":
    "Thank you. I'll look at it within 24 hours and take the book down if it breaks the terms of use.",
  "Bücher von {name} siehst du nicht mehr. Im Profil kannst du das zurücknehmen.": "You won't see books from {name} anymore. You can undo that in your profile.",
  "„{title}“ von {name}. Was stimmt nicht?": "“{title}” by {name}. What's wrong?",
  Grund: "Reason",
  "Magst du kurz sagen, worum es geht? (freiwillig)": "Want to say briefly what it's about? (optional)",
  "Bücher von {name} nicht mehr zeigen": "Stop showing books from {name}",
  "Sendet …": "Sending …",
  Melden: "Report",

  // Profil
  "Dein Profil": "Your profile",
  "Melde dich an, dann siehst du hier deine Bücher, deine geteilten Links und dein Konto.": "Sign in to see your books, your shared links and your account here.",
  "Eigene Bücher": "Your books",
  "Fotos darin": "Photos in them",
  Hingelegt: "Handed over",
  "Ohne Namen": "No name",
  "Angemeldet mit {provider}": "Signed in with {provider}",
  Leseausweis: "Library card",
  "seit {date}": "since {date}",
  "Konnte nicht alles laden: {error}": "Couldn't load everything: {error}",
  "Hingelegt für": "Handed over to",
  "Noch niemand. Im Bücherzimmer legst du ein Buch über „Mehr …“ und „Hinlegen für …“ einem Freund hin.":
    "No one yet. In your library, hand a book to a friend via “More …” and “Hand over to …”.",
  "ruht, im Papierkorb": "paused, in the trash",
  "liegt bereit": "ready",
  Konto: "Account",
  "Name ändern": "Change name",
  "Steht als Absender auf Büchern und Zetteln": "Shown as the sender on books and notes",
  Abmelden: "Sign out",
  "Konto löschen": "Delete account",
  "Mit allen Büchern und Links": "With all books and links",
  "Deine Bücher sieht nur, wem du einen Link gibst. Den Aufbau eines Buchs sicherst du beim Bearbeiten unter „Verlauf“ als Datei; die Fotos bleiben in deinem Konto.":
    "Only people you give a link to see your books. While editing, you can save a book's structure as a file under “History”; the photos stay in your account.",
  Ausgeblendet: "Hidden",
  "Bücher dieser Personen landen nicht mehr in deinem Bücherzimmer.": "Books from these people no longer land in your library.",
  "Wieder zeigen": "Show again",
  "Rechtliches und Hilfe": "Legal and help",
  "Schreib mir": "Write to me",
  "Für Fragen, Fehler oder einen Inhalt, der nicht hierher gehört. Calima ist nicht mit Fujifilm verbunden; FUJIFILM und FUJI sind Marken der FUJIFILM Corporation.":
    "For questions, bugs or content that doesn't belong here. Calima is not affiliated with Fujifilm; FUJIFILM and FUJI are trademarks of FUJIFILM Corporation.",
  "Anmeldung bestätigen": "Confirming sign-in",
  "{what} werden gelöscht": "Deleting: {what}",
  "Konto wird gelöscht": "Deleting account",
  "{error} Was schon gelöscht ist, bleibt gelöscht. Versuch es bitte nochmal.": "{error} What's already deleted stays deleted. Please try again.",
  "Gelöscht wird alles, was zu deinem Konto gehört:": "Everything that belongs to your account will be deleted:",
  "deine Bücher{books} mit allen Fotos{photos}, Zwischenständen und dem Papierkorb": "your books{books} with all photos{photos}, saved versions and the trash",
  "deine geteilten Links{shares} samt Zetteln und Eselsohren der Gäste": "your shared links{shares}, including guests' notes and dog-ears",
  "deine Ablage „Für dich“ und deine eigenen Rezepte": "your “For you” tray and your own recipes",
  "dein Konto bei Calima": "your Calima account",
  "Wer einen Link von dir hat, kann das Buch danach nicht mehr öffnen.": "Anyone with a link from you won't be able to open the book afterwards.",
  "Das lässt sich nicht rückgängig machen.": "This can't be undone.",
  "Zur Sicherheit meldest du dich dafür noch einmal an.": "To be safe, you'll sign in once more for this.",
  "Konto endgültig löschen": "Delete account for good",
  Meldungen: "Reports",
  "Keine offenen Meldungen.": "No open reports.",
  "„{title}“ von {name}": "“{title}” by {name}",
  "Macher-ID {id}": "Maker ID {id}",
  Ansehen: "View",
  "Link sperren": "Block link",
  "Erledigt, alles in Ordnung": "Done, all fine",
  "So steht es als Absender auf neuen Büchern und Zetteln.": "This is how it appears as the sender on new books and notes.",
  Name: "Name",
  Speichern: "Save",

  // Konto gelöscht, nicht gefunden
  "Dein Konto ist gelöscht.": "Your account is deleted.",
  "Deine Bücher, Fotos und geteilten Links sind weg. Danke, dass du Calima ausprobiert hast.": "Your books, photos and shared links are gone. Thanks for trying Calima.",
  "Diese Seite gibt es nicht.": "This page doesn't exist.",
  "Vielleicht ist der Link alt oder unvollständig.": "Maybe the link is old or incomplete.",
};
