// Englisch für die Bühne (Doppelseite gestalten), Tafel-Ansicht, Zettel und Gradationskurve (siehe index.ts)

export const STAGE: Record<string, string> = {
  // Bühne: Kopf und Verlauf
  "Doppelseite {n}": "Spread {n}",
  "Doppelseite {n} gestalten": "Design spread {n}",
  "Zur Übersicht": "Back to overview",
  Übersicht: "Overview",
  "frei gestaltet, fixiert": "freely designed, fixed",
  "automatisch, wird beim ersten Handgriff frei": "automatic, becomes free with your first change",
  "Auf Vorschlag zurücksetzen": "Reset to suggestion",
  "Fotos bearbeiten": "Edit photos",
  Verlauf: "History",
  "Verlauf und Raster": "History and grid",
  Rückgängig: "Undo",
  Wiederholen: "Redo",
  Mehr: "More",
  "Raster ausblenden": "Hide grid",
  "Raster zeigen": "Show grid",
  "Raster zeigen (G)": "Show grid (G)",
  Ebenen: "Layers",
  Ansicht: "View",
  "Ganze Doppelseite": "Whole spread",
  Links: "Left",
  Rechts: "Right",
  Werkzeuge: "Tools",

  // Bühne: Werkzeuge und Fächer
  Auswahl: "Select",
  Stift: "Pen",
  Radierer: "Eraser",
  Fotos: "Photos",
  Text: "Text",
  Zeichnen: "Draw",
  Formen: "Shapes",
  Linie: "Line",
  Pfeil: "Arrow",
  Rechteck: "Rectangle",
  Kreis: "Circle",
  Klebestreifen: "Tape",
  Überschrift: "Heading",
  Absatz: "Paragraph",
  Notiz: "Note",
  "Ein paar Sätze zu diesem Tag.": "A few sentences about this day.",
  Breite: "Width",
  "Breite {w}": "Width {w}",
  fein: "fine",
  mittel: "medium",
  kräftig: "bold",
  "Stift: auf der Seite zeichnen. Esc beendet.": "Pen: draw on the page. Esc to stop.",
  "Radierer: über Striche wischen.": "Eraser: swipe over strokes.",
  "{shape}: auf der Seite aufziehen.": "{shape}: drag it out on the page.",
  "Mit dem Stift zeichnen; der Finger zeichnet nicht, sobald ein Stift da war.":
    "Draw with the pencil; your finger stops drawing once a pencil has been used.",
  "Zeichnen mit Maus oder Stift. Esc oder V beendet.": "Draw with mouse or pen. Esc or V to stop.",
  "Über Striche wischen löscht sie. Formen und Fotos bleiben.": "Swipe over strokes to erase them. Shapes and photos stay.",
  "{shape} aufziehen; ein Klick legt sie in Standardgröße hin.": "{shape}: drag it out; a click places it at default size.",
  "Shift: 45°-Schritte.": "Shift: 45° steps.",
  "Shift: Quadrat bzw. Kreis.": "Shift: square or circle.",
  "Alt: ohne Einrasten.": "Alt: no snapping.",
  "Form wählen, dann auf der Seite aufziehen.": "Pick a shape, then drag it out on the page.",
  "{shape} aufziehen, ein Tipp legt sie hin.": "{shape}: drag it out, or tap to place it.",
  "Antippen legt den Text auf die Seite, Ziehen an eine bestimmte Stelle":
    "Tap to put the text on the page, drag to place it somewhere specific",
  "Klicken legt den Text auf die Seite, Ziehen an eine bestimmte Stelle":
    "Click to put the text on the page, drag to place it somewhere specific",

  // Bühne: Fotos des Buchs
  "Fotos des Buchs": "The book's photos",
  "Foto auf diese Doppelseite holen: {title}, {from}": "Bring photo to this spread: {title}, {from}",
  "ohne Titel": "untitled",
  beiseitegelegt: "set aside",
  "von Doppelseite {n}": "from spread {n}",
  Beiseite: "Set aside",
  "Alle Fotos": "All photos",
  "antippen oder nach oben auf die Seite ziehen": "tap or drag up onto the page",
  "ziehen oder antippen legt sie auf die Seite": "drag or tap to put them on the page",
  ", von anderen Doppelseiten wandern sie herüber": ", photos from other spreads move over",
  "Alle Fotos des Buchs liegen schon auf dieser Doppelseite.": "All of the book's photos are already on this spread.",
  "Das Foto liegt schon auf dieser Doppelseite.": "That photo is already on this spread.",
  "Kein Platz mehr: höchstens {n} Fotos pro Seite. Erst ein Foto beiseitelegen.":
    "No room left: at most {n} photos per page. Set a photo aside first.",

  // Bühne: Ansagen für Screenreader
  "linke Seite": "left page",
  "rechte Seite": "right page",
  ", Spalte {n}": ", column {n}",
  ", Zeile {n}": ", row {n}",
  "Foto {no}": "Photo {no}",
  "Zeichnung, 1 Strich": "Drawing, 1 stroke",
  "Zeichnung, {n} Striche": "Drawing, {n} strokes",
  "{what} hinzugefügt: {where}. Jetzt tippen.": "{what} added: {where}. Start typing.",
  "{what} hinzugefügt: {where}": "{what} added: {where}",
  "Foto hinzugefügt: {where}": "Photo added: {where}",
  "Strich radiert": "Stroke erased",
  "Strich {n}": "Stroke {n}",
  "Zeichnung begonnen": "Drawing started",
  "Größe {w} × {h}": "Size {w} × {h}",
  "{what} eingefügt: {where}": "{what} pasted: {where}",
  "{what} entfernt": "{what} removed",
  Kopiert: "Copied",
  Ausgeschnitten: "Cut",
  "Liegt schon ganz vorn.": "Already at the front.",
  "Liegt schon ganz hinten.": "Already at the back.",
  "Nach vorn gelegt": "Brought forward",
  "Nach hinten gelegt": "Sent backward",
  Zugeschnitten: "Cropped",

  // Bühne: Kontextmenü
  Aktionen: "Actions",
  Kopieren: "Copy",
  Ausschneiden: "Cut",
  Duplizieren: "Duplicate",
  Einfügen: "Paste",
  "Hier einfügen": "Paste here",
  "Ganz nach vorn": "Bring to front",
  "Nach vorn": "Bring forward",
  "Nach hinten": "Send backward",
  "Ganz nach hinten": "Send to back",
  Zuschneiden: "Crop",
  Doppeltippen: "Double-tap",
  Doppelklick: "Double-click",
  "Ausschnitt-Dialog …": "Crop dialog …",
  "Unterschrift auf der Seite": "Caption on the page",
  "Aus dem Buch nehmen": "Remove from book",
  Entf: "Del",
  "Text schreiben": "Write text",
  "Helle Schrift": "Light text",
  "{what} hier": "{what} here",
  "Form hier": "Shape here",
  Ebene: "Layer",
  Art: "Kind",
  Löschen: "Delete",

  // Bühne: Zuschneiden
  Fertig: "Done",
  Abbrechen: "Cancel",
  "Ausschnitt genauer einstellen": "Adjust crop precisely",
  "Bild ziehen verschiebt · Ecken am Bild vergrößern · Griffe am Rahmen schneiden":
    "Drag image to move · Image corners to enlarge · Frame handles to crop",
  Originalformat: "Original ratio",

  // Bühne: Fach am Handy, Seitenleiste
  Foto: "Photo",
  Bearbeiten: "Edit",
  Ausschnitt: "Crop",
  "Unterschrift aus": "Caption off",
  "Unterschrift an": "Caption on",
  "Mehr zum Foto": "More for this photo",
  "Ziehen verschiebt, zwei Finger ändern die Größe.": "Drag to move, two fingers to resize.",
  "Doppeltippen auf einen Text schreibt.": "Double-tap a text to write.",
  "{what} schreiben": "Write {what}",
  "nach vorn": "forward",
  "nach hinten": "backward",
  "Was oben liegt": "What's on top",
  "Oben liegt vorn. Antippen wählt, auch was verdeckt ist.": "Top is in front. Tap to select, even what's hidden.",
  Textrahmen: "Text box",
  Stil: "Style",
  "(für Text auf dunklen Fotos)": "(for text on dark photos)",
  "Der Text läuft unten aus dem Satzspiegel. Kürzen oder den Rahmen breiter ziehen.":
    "The text runs past the bottom margin. Shorten it or make the box wider.",
  "Textrahmen entfernen": "Remove text box",
  Farbe: "Color",
  Kontur: "Outline",
  Fläche: "Fill",
  Strich: "Stroke",
  gestrichelt: "dashed",
  "{what} entfernen": "Remove {what}",
  Zeichnung: "Drawing",
  "1 Strich.": "1 stroke.",
  "{n} Striche.": "{n} strokes.",
  "Ziehen verschiebt, die Griffe skalieren. Einzelne Striche löscht der Radierer (E).":
    "Drag to move, handles to scale. The eraser (E) removes single strokes.",
  "Alle Striche umfärben": "Recolor all strokes",
  "Zeichnung entfernen": "Remove drawing",
  Titel: "Title",
  "(sonst im Kopf)": "(otherwise in the header)",
  "Ebene und Kopie": "Layer and copy",
  "Kopie und Ebene": "Copy and layer",

  // Bühne: Hilfe unter der Doppelseite
  "Zwei Finger zoomen, Doppeltippen aufs Papier holt eine Seite groß. Ziehen verschiebt, Doppeltippen auf ein Foto schneidet zu, langes Drücken auf ein Element zeigt alles, was damit geht, aufs leere Papier legt etwas an.":
    "Two fingers zoom, double-tap the paper to bring a page up close. Drag to move, double-tap a photo to crop, long-press an element to see everything you can do with it, or empty paper to add something.",
  "Zwei Finger zoomen und verschieben die Ansicht, Doppeltippen aufs freie Papier holt eine Seite groß und wieder zurück. Zwei Finger auf dem gewählten Foto ändern seine Größe.":
    "Two fingers zoom and pan the view, double-tap empty paper to bring a page up close and back. Two fingers on the selected photo resize it.",
  "Ziehen verschiebt ein Foto oder einen Text, die Griffe ändern die Größe. Doppeltippen auf ein Foto schneidet zu, auf einen Text schreibt.":
    "Drag to move a photo or text, handles to resize. Double-tap a photo to crop, a text to write.",
  "Lange drücken auf ein Element zeigt alles, was damit geht, aufs leere Papier legt etwas an.":
    "Long-press an element to see everything you can do with it, or empty paper to add something.",
  "Ziehen verschiebt, die Griffe ändern die Größe. Doppelklick auf ein Foto schneidet zu, auf einen Text schreibt, aufs Papier legt neuen Text an.":
    "Drag to move, handles to resize. Double-click a photo to crop, a text to write, the paper to add new text.",
  "Kanten rasten am Raster ein,": "Edges snap to the grid,",
  "beim Ziehen setzt frei.": "while dragging turns snapping off.",
  "Tastatur:": "Keyboard:",
  "wählt, Pfeile verschieben um eine Spalte oder Zeile,": "selects, arrows move by one column or row,",
  "+ Pfeile ändern die Größe,": "+ arrows resize,",
  "schneidet zu,": "crops,",
  "nimmt heraus,": "removes,",
  "kopiert,": "copies,",
  "dupliziert,": "duplicates,",
  "zeigt das Raster.": "shows the grid.",

  // Text gestalten
  "Text gestalten": "Style text",
  "Schriftart: {font}": "Font: {font}",
  Grotesk: "Grotesque",
  Serif: "Serif",
  Schreibmaschine: "Typewriter",
  Handschrift: "Handwriting",
  Größe: "Size",
  kleiner: "smaller",
  größer: "larger",
  "Größe in Punkt": "Size in points",
  Fett: "Bold",
  F: "B",
  Kursiv: "Italic",
  K: "I",
  "Ausrichtung|Text": "Alignment",
  linksbündig: "align left",
  mittig: "center",
  rechtsbündig: "align right",
  "Farbe {color}": "Color {color}",
  "Eigene Farbe": "Custom color",
  keine: "none",
  "keine Fläche": "no fill",
  Tinte: "Ink",
  Grau: "Gray",
  Papier: "Paper",
  Schwarz: "Black",
  Weiß: "White",
  Ringelblume: "Marigold",
  Ziegel: "Brick",
  Meer: "Sea",
  Salbei: "Sage",
  Einband: "Cover",

  // Tafeln
  "Tafel {no}": "Plate {no}",
  "Tafel {no}: {title}": "Plate {no}: {title}",
  "{plate} vergrößern": "Enlarge {plate}",
  "Zu {plate}": "Go to {plate}",
  "Voriges Bild": "Previous image",
  "Nächstes Bild": "Next image",
  Schließen: "Close",

  // Zettel
  "Zettel an {who}": "Note for {who}",
  "Dein Zettel bei {who}": "Your note with {who}",
  "Zettel von {who}": "Note from {who}",
  "Dein Zettel bei {who} öffnen": "Open your note with {who}",
  "Zettel von {who} öffnen": "Open note from {who}",
  "Schreib {who} etwas zu dieser Stelle …": "Write {who} something about this spot …",
  Weg: "Discard",
  Hinlegen: "Leave it",
  "bei {who}": "with {who}",
  "von {who}": "from {who}",
  "Zettel klein machen": "Minimize note",
  "Der Zettel ist nicht angekommen. Versuch es bitte nochmal.": "The note didn't arrive. Please try again.",

  // Gradationskurve
  Gradationskurve: "Tone curve",
  Schwarzpunkt: "Black point",
  Weißpunkt: "White point",
  "Punkt {i} von {n}": "Point {i} of {n}",
  "Eingang {x}, Ausgang {y}": "Input {x}, output {y}",
};
