// Englisch für Werkbank (editor.tsx), Fotostudio, Tisch und Buchdateien (siehe index.ts)

export const WORKBENCH: Record<string, string> = {
  // Werkbank: Kopf und Speichern
  "Ein Buch gestalten": "Design a book",
  "Melde dich an, dann ziehst du deine Fotos hier hinein. Rezepte und Kameradaten werden gelesen, GPS-Daten fallen weg.":
    "Sign in, then drag your photos in here. Recipes and camera data are read, GPS data is dropped.",
  "Speichert …": "Saving …",
  Gespeichert: "Saved",
  "Offline gespeichert, geht raus, sobald Netz da ist": "Saved offline, goes out once you're connected",
  "Offline gespeichert": "Saved offline",
  "Speichern fehlgeschlagen": "Saving failed",
  Ansehen: "View",
  "Hinlegen für …": "Hand over to …",
  "Hinlegen …": "Hand over …",

  // Werkbank: Fotos hineinziehen
  Doppelseiten: "Spreads",
  "Weitere Fotos hineinziehen": "Drag in more photos",
  "Fotos hier hineinziehen": "Drag photos in here",
  "Weitere Fotos vom Handy": "More photos from your phone",
  "Fotos vom Handy": "Photos from your phone",
  "Originale direkt von der Kamera bringen ihr Fuji-Rezept mit, Lightroom-Exporte mit „Alle Metadaten“ ihre Einstellungen. Beim Hochladen werden die Fotos neu gespeichert, GPS und Seriennummer fallen weg. JPEG, HEIC und DNG vom iPhone.":
    "Originals straight from the camera bring their Fuji recipe, Lightroom exports with “All metadata” their settings. Uploading saves the photos anew, dropping GPS and serial number. JPEG, HEIC and DNG from the iPhone.",
  "Fotos auswählen": "Choose photos",
  "bis zu {max} Fotos": "up to {max} photos",
  "Buch ist voll": "book is full",
  "noch {n} frei": "{n} left",
  "{done} von {total} Fotos im Buch": "{done} of {total} photos in the book",
  "Fortschritt je Foto": "Progress per photo",
  "liest …": "reading …",
  "lädt hoch …": "uploading …",
  fertig: "done",
  "Kein Foto": "Not a photo",
  "Ließ sich nicht öffnen": "Couldn't be opened",
  "Diese Fotos kamen nicht als Dateien an. Aus der Fotos-App bitte erst in den Finder ziehen oder „Fotos auswählen“ nutzen.":
    "These photos didn't arrive as files. From the Photos app, drag them into the Finder first or use “Choose photos”.",
  "{n} von {all} Fotos aufgenommen, damit ist das Buch voll (bis zu {max} Fotos). Die übrigen {over} passen in ein zweites Buch.":
    "{n} of {all} photos added, which fills the book (up to {max} photos). The other {over} fit in a second book.",
  "Das Buch ist schon voll (bis zu {max} Fotos). Die {over} Fotos passen in ein zweites Buch.":
    "The book is already full (up to {max} photos). The {over} photos fit in a second book.",

  // Werkbank: Doppelseiten
  "1 Doppelseite": "1 spread",
  "{n} Doppelseiten": "{n} spreads",
  Textseite: "Text page",
  "Fixierte Doppelseiten und Textseiten bleiben, wie sie sind": "Locked spreads and text pages stay as they are",
  "Automatisch gestalten": "Auto layout",
  "bleibt, wie du es gesetzt hast.": "stays the way you set it.",
  "Doppelseite {n} · frei": "Spread {n} · free",
  "Doppelseite {n} lösen": "Unlock spread {n}",
  "Doppelseite {n} fixieren": "Lock spread {n}",
  "fixiert: die Automatik lässt sie in Ruhe": "locked: auto layout leaves it alone",
  "frei: die Automatik darf sie neu ordnen": "free: auto layout may rearrange it",
  Gestalten: "Design",
  "Fotos von Doppelseite {n} bearbeiten": "Edit photos of spread {n}",
  "Fotos bearbeiten: Looks, Vorschläge, Feinschliff": "Edit photos: looks, suggestions, fine-tuning",
  "Anderes Layout für Doppelseite {n}, jetzt {k} von {all}": "Another layout for spread {n}, now {k} of {all}",
  "Layout {k} von {all}": "Layout {k} of {all}",
  "Anderes Layout": "Another layout",
  "Doppelseite {n} nach vorn": "Move spread {n} earlier",
  "Doppelseite {n} nach hinten": "Move spread {n} later",
  "Doppelseite {n} entfernen, die Fotos werden beiseitegelegt": "Remove spread {n}, the photos are set aside",
  "Doppelseite entfernen, die Fotos werden beiseitegelegt": "Remove spread, the photos are set aside",
  "Doppelklick: gestalten": "Double-click: design",
  "Foto auswählen: {title}": "Select photo: {title}",
  "Text bearbeiten": "Edit text",
  wichtig: "important",
  "Der Text ist etwa {n} Zeilen zu lang für die Seite.": "The text is about {n} lines too long for the page.",
  "Doppelseite {n} entfernt, die Fotos sind beiseitegelegt.": "Spread {n} removed, the photos are set aside.",
  "Doppelseite {n} entfernt.": "Spread {n} removed.",
  "Auf dieser Doppelseite ist kein Platz frei. Öffne sie mit „Gestalten“ und mach Platz.":
    "There's no free space on this spread. Open it with “Design” and make room.",

  // Werkbank: Beiseitegelegt
  Beiseitegelegt: "Set aside",
  "Beiseitegelegt, nicht mehr im Buch.": "Set aside, no longer in the book.",
  "Nicht im Buch. „Ins Buch“ legt ein Foto zurück.": "Not in the book. “Into the book” puts a photo back.",
  "Beiseitegelegtes Foto auswählen: {title}": "Select set-aside photo: {title}",
  "{title} ins Buch": "{title} into the book",
  "Ins Buch": "Into the book",
  Beiseitelegen: "Set aside",

  // Werkbank: Buch und Einband
  "Einband: Titelbild wählen": "Cover: choose cover photo",
  Buch: "Book",
  "Titelbild …": "Cover photo …",
  Titelbild: "Cover photo",
  "Zeile darunter": "Line below",
  "Leer lassen: Anzahl der Fotos": "Leave empty: number of photos",
  "Farbe des Einbands": "Cover color",
  "Tippe auf ein Foto, es kommt auf den Einband. Fotos mit Stern stehen vorn.": "Tap a photo to put it on the cover. Starred photos come first.",
  "Foto {n}": "Photo {n}",

  // Werkbank: gewähltes Foto
  "Fuji-Rezept erkannt: {film}": "Fuji recipe found: {film}",
  "Lightroom-Einstellungen erkannt": "Lightroom settings found",
  "Kein Rezept in der Datei, Kameradaten: {device}": "No recipe in the file, camera data: {device}",
  "Keine Metadaten in der Datei (z. B. aus einem Messenger)": "No metadata in the file (e.g. from a messenger)",
  "Wichtig: kommt groß ins Buch": "Important: goes in big",
  "Als wichtig markieren": "Mark as important",
  "Zusatz (Ort, Notiz)": "Extra (place, note)",
  "Beschreibung für Screenreader": "Description for screen readers",
  "Ausschnitt …": "Crop …",
  "Bearbeiten …": "Edit …",
  "für andere Fotos und Bücher, in Calima nachempfunden": "for other photos and books, recreated in Calima",
  "Fuji-Rezept mitnehmen": "Take Fuji recipe",
  "Lightroom-Werte mitnehmen": "Take Lightroom values",
  "Farbe und Licht von einem anderen Foto, der Zuschnitt bleibt. ⇧⌘V nimmt den zuletzt mitgenommenen":
    "Color and light from another photo, the crop stays. ⇧⌘V applies the one you took last",
  "Übernehme …": "Applying …",
  "Look übernehmen": "Apply look",
  "Zuletzt mitgenommen": "Recently taken",
  nachempfunden: "recreated",
  "In diesem Buch": "In this book",
  "Auf dem Einband": "On the cover",
  "Auf den Einband": "Put on cover",
  "← Nach vorn": "← Previous spread",
  "Nach hinten →": "Next spread →",
  "Ziehen auf eine andere Doppelseite verschiebt das Foto auch. Tastatur: Alt + ← / → , Entf legt es beiseite.":
    "Dragging onto another spread moves the photo too. Keyboard: Alt + ← / → , Delete sets it aside.",
  "Dieses Foto hat noch keine Einstellungen zum Kopieren.": "This photo has no settings to copy yet.",
  "„{name}“ mitgenommen, in Calima nachempfunden. Liegt im Fotostudio oben bei „Deine Looks“.":
    "Took “{name}”, recreated in Calima. It's in the Photo studio under “Your looks”.",
  "„{name}“ mitgenommen. Liegt im Fotostudio oben bei „Deine Looks“.": "Took “{name}”. It's in the Photo studio under “Your looks”.",
  "„{name}“ übernommen, nachempfunden. Der Zuschnitt bleibt.": "Applied “{name}”, recreated. The crop stays.",
  "„{name}“ übernommen. Der Zuschnitt bleibt.": "Applied “{name}”. The crop stays.",
  "Übernehmen hat nicht geklappt. Prüf die Verbindung und versuch es noch einmal.": "Applying didn't work. Check your connection and try again.",
  "Erst bei einem Foto einen Look mitnehmen.": "Take a look from a photo first.",

  // Werkbank: Textseite
  "Überschrift (optional)": "Heading (optional)",
  "z. B. Drei Tage am Meer": "e.g. Three days by the sea",
  "Ein paar Sätze zu eurer Geschichte. Leerzeile = neuer Absatz.": "A few sentences about your story. Blank line = new paragraph.",
  Schrift: "Type",
  Groß: "Large",
  "Passt auf die Seite. Daneben kann ein Foto stehen: einfach hierher ziehen.": "Fits on the page. A photo can go next to it: just drag it here.",
  "Etwa {n} Zeilen zu lang für die Seite: kürzen oder „Absatz“ wählen.": "About {n} lines too long for the page: shorten it or choose “Paragraph”.",
  "Etwa {n} Zeilen zu lang für die Seite: kürzen.": "About {n} lines too long for the page: shorten it.",
  "Tippe auf ein Foto für Titel, Ausschnitt und Stern, oder auf eine Textseite zum Schreiben.":
    "Tap a photo for title, crop and star, or a text page to write.",
  "Doppelklick auf eine Doppelseite öffnet sie zum Gestalten. Fotos und Doppelseiten lassen sich ziehen.":
    "Double-click a spread to design it. Photos and spreads can be dragged.",
  "„Gestalten“ öffnet eine Doppelseite zum freien Anordnen.": "“Design” opens a spread for free arrangement.",
  "Loslassen, dann kommen die Fotos ins Buch": "Let go and the photos go into the book",

  // Werkbank: Verlauf (Namen der Zwischenstände werden auf Deutsch gespeichert und beim Zeigen übersetzt)
  Zwischenstand: "Snapshot",
  "vor dem Entfernen einer Doppelseite": "before removing a spread",
  "vor dem Zurücksetzen einer Doppelseite": "before resetting a spread",
  "vor „Automatisch gestalten“": "before “Auto layout”",
  "vor dem Zurückholen": "before restoring",
  "Eigener Stand": "Own version",
  "gerade eben": "just now",
  Fotobuch: "Photo book",
  "Projekt gesichert.": "Project saved.",
  "Die Datei ließ sich nicht anlegen. Versuch es bitte noch einmal.": "The file couldn't be created. Please try again.",
  "Zwischenstände entstehen von selbst vor großen Änderungen und alle zehn Minuten.": "Snapshots are made automatically before big changes and every ten minutes.",
  "Eigenen Stand benennen": "Name your own version",
  Sichern: "Save",
  "Lade …": "Loading …",
  "Noch keine Zwischenstände.": "No snapshots yet.",
  Zwischenstände: "Snapshots",
  "{label} vom {when} zurückholen": "Restore {label} from {when}",
  Zurückholen: "Restore",
  "Ältere zeigen ({n})": "Show older ({n})",
  "Projekt als Datei sichern …": "Save project as file …",
  "Projekt als Datei sichern": "Save project as file",
  "Enthält Aufbau und Texte, nicht die Fotos: Die bleiben in deinem Konto. Wieder öffnen: Bücherzimmer › Neues Buch › Aus Datei öffnen.":
    "Contains layout and texts, not the photos: those stay in your account. To reopen: Library › New book › Open from file.",

  // Fotostudio
  Fotostudio: "Photo studio",
  "Ein Abzug": "One print",
  "{n} Abzüge": "{n} prints",
  heute: "today",
  gestern: "yesterday",
  "{prints} in einem Stapel": "{prints} in one stack",
  "{prints} in {n} Stapeln": "{prints} in {n} stacks",
  "zuletzt {when}": "last {when}",
  "Fotos bearbeiten, sichern oder in ein Buch legen. Gern mehrere auf einmal.": "Edit photos, save them or put them in a book. Several at once is fine.",
  Abzüge: "Prints",
  "Neue Fotos": "New photos",
  "Fotos wählen": "Choose photos",
  "Ein Abzug öffnet das Foto wieder, ein Stapel die ganze Serie, so wie du sie bearbeitet hast. Nichts davon wird hochgeladen.":
    "A print reopens the photo, a stack the whole series, just as you edited it. None of it is uploaded.",
  "{name}, {when} bearbeitet. Öffnen": "{name}, edited {when}. Open",
  "Stapel mit {n} Fotos, {when} bearbeitet. Öffnen": "Stack of {n} photos, edited {when}. Open",
  "{n} Fotos": "{n} photos",
  "1 Foto": "1 photo",
  "Höchstens {max} Fotos auf einmal, die ersten {max} sind offen.": "At most {max} photos at once, the first {max} are open.",
  "Fotos über 60 MB bleiben draußen.": "Photos over 60 MB are left out.",
  "Dieses Foto lässt sich nicht öffnen.": "This photo can't be opened.",
  "Dieses Foto lässt sich nicht öffnen: {reason}.": "This photo can't be opened: {reason}.",
  "Ein Foto ließ sich nicht öffnen.": "One photo couldn't be opened.",
  "{n} Fotos ließen sich nicht öffnen.": "{n} photos couldn't be opened.",
  "Ein Foto ist offen.": "One photo is open.",
  "{n} Fotos sind offen.": "{n} photos are open.",
  "Öffne {i} von {n} …": "Opening {i} of {n} …",
  "Wird geöffnet …": "Opening …",
  Unbearbeitet: "Unedited",
  Vorschlag: "Suggestion",
  Filmlook: "Film look",
  Dynamikbereich: "Dynamic range",
  "Lichter / Schatten": "Highlights / shadows",
  "Color Chrome / FX Blau": "Color Chrome / FX Blue",
  Zuschnitt: "Crop",
  Aus: "Off",
  Leicht: "Light",
  Stark: "Strong",

  // Fotostudio: fertig
  "{n} Fotos fertig": "{n} photos done",
  "Fertig bearbeitet": "Done editing",
  "Rechne {i} von {n} …": "Processing {i} of {n} …",
  "Wird vorbereitet …": "Preparing …",
  "Alle {n} in Fotos sichern …": "Save all {n} to Photos …",
  "In Fotos sichern …": "Save to Photos …",
  "Alle herunterladen": "Download all",
  Herunterladen: "Download",
  "Die Dateien ließen sich nicht rechnen.": "The files couldn't be processed.",
  "Die Datei ließ sich nicht rechnen.": "The file couldn't be processed.",
  "Im nächsten Fenster „{n} Bilder sichern“ wählen. Ohne Ortsangabe.": "In the next window, choose “Save {n} Images”. No location data.",
  "Im nächsten Fenster „Bild sichern“ wählen. Ohne Ortsangabe.": "In the next window, choose “Save Image”. No location data.",
  "Eine ZIP-Datei mit {n} JPEGs, {px} px, ohne Ortsangabe.": "A ZIP file with {n} JPEGs, {px} px, no location data.",
  "JPEG, {px} px, ohne Ortsangabe.": "JPEG, {px} px, no location data.",
  "Noch einmal versuchen": "Try again",
  "Für die Datei schärfen": "Sharpen for the file",
  "Alle in ein Buch legen …": "Put all in a book …",
  "In ein Buch legen …": "Put in a book …",
  "Weiter bearbeiten": "Keep editing",
  "Stapel vom Pult nehmen": "Take stack off the desk",
  "Vom Pult nehmen": "Take off the desk",
  "Die Dateien ließen sich nicht sichern. Versuch es bitte noch einmal.": "The files couldn't be saved. Please try again.",
  "Die Datei ließ sich nicht sichern. Versuch es bitte noch einmal.": "The file couldn't be saved. Please try again.",
  "Gesichert.": "Saved.",
  "Liegt in deinen Downloads.": "It's in your downloads.",

  // Fotostudio: in ein Buch legen
  "In welches Buch?": "Which book?",
  Zurück: "Back",
  "Die {n} Fotos kommen in die Ablage.": "The {n} photos are set aside in the book.",
  "Das Foto kommt in die Ablage.": "The photo is set aside in the book.",
  "Deine Seiten bleiben, wie sie sind.": "Your pages stay as they are.",
  "Deine Bücher": "Your books",
  "Neues Buch mit diesen Fotos": "New book with these photos",
  "Neues Buch mit diesem Foto": "New book with this photo",
  "ein neues Buch": "a new book",
  "Lege Foto {i} von {n} in {into} …": "Putting photo {i} of {n} in {into} …",
  "Lege das Foto in {into} …": "Putting the photo in {into} …",
  "Lege ein neues Buch an …": "Creating a new book …",
  "Die {n} Fotos liegen in der Ablage von „{name}“.": "The {n} photos are set aside in “{name}”.",
  "Liegt in der Ablage von „{name}“.": "Set aside in “{name}”.",
  "Neues Buch mit {n} Fotos angelegt.": "New book with {n} photos created.",
  "Neues Buch mit diesem Foto angelegt.": "New book with this photo created.",
  Öffnen: "Open",
  "Hat nicht geklappt. Prüf die Verbindung und tipp noch einmal. ({error})": "That didn't work. Check your connection and tap again. ({error})",

  // Fotos lesen
  "DNG ohne Vorschaubild, bitte als JPEG exportieren": "DNG without preview image, please export as JPEG",
  "Bildformat wird nicht unterstützt": "Image format not supported",
  "Kodieren fehlgeschlagen": "Encoding failed",

  // Buchdatei
  "Ein Foto in der Datei ist beschädigt.": "A photo in the file is damaged.",
  "Die Datei verweist auf Fotos außerhalb von Calima.": "The file points to photos outside Calima.",
  "Ein Text in der Datei ist zu lang.": "A text in the file is too long.",
  "Die Datei verweist auf ein Preset außerhalb von Calima.": "The file points to a preset outside Calima.",
  "Die Datei enthält einen ungültigen Link.": "The file contains an invalid link.",
  "Ein Preset in der Datei ist zu groß.": "A preset in the file is too large.",
  "Das ist keine Calima-Buchdatei. Sie endet auf .calima.json.": "This isn't a Calima book file. It ends in .calima.json.",
  "Die Datei stammt aus einer neueren Calima-Version.": "The file comes from a newer version of Calima.",
  "Die Datei enthält keine gültige Fotoliste.": "The file contains no valid photo list.",
  "Die Datei enthält keine gültigen Doppelseiten.": "The file contains no valid spreads.",
  "Das Seitenformat in der Datei ist beschädigt.": "The page format in the file is damaged.",

  // auch im Bücherzimmer (library.ts), gleich übersetzt
  Bearbeiten: "Edit",
  "Ohne Titel": "Untitled",
  Titel: "Title",
  Einband: "Cover",
  Rezept: "Recipe",
  "Die Datei ist zu groß für eine Calima-Buchdatei.": "This file is too large for a Calima book file.",

  // Tisch
  Tafeln: "Plates",
  "1 Tafel": "1 plate",
  "{n} Tafeln": "{n} plates",
  "{title} aufschlagen": "Open {title}",
  "Buch aufschlagen": "Open book",
  "Tisch mit Fotobüchern": "Table with photo books",
  "Deine Bücher liegen jetzt im Bücherzimmer": "Your books are now in the Library",
};
